//! exit_code: 1
fn main() {
    continue;  // diag: error(continue_outside_of_loop): "continue outside of loop"
}
